### ISSUE TITLE
Provide a setter

### ISSUE THREAD

**Issue by nervo** [qri-io/jsonpointer#7]
What about providing a setter method on pointer ?
Today, only a getter (`Eval`) is available :)

**Comment by Arqu** [comment]
I think you shouldn't directly modify the Pointer when using it. The way I recommend navigating is by traversing the JSON and building the pointer using `Descendant`. 

Otherwise you can always manually recompile the pointer by manipulating the string representation and just `.Parse` into a new pointer. 

Lastly, the Pointer is just a type alias for `[]string`, so you should be able to cast, manipulate and cast back.

Hope this helps. I will close the issue for now, but can reopen if you feel it needs further exploration.

**Comment by nervo** [comment]
Thanks for clarifications :)
